version: "3.8"
services:
  app:
    image: dtrinhit/docker-swarm-ip:latest  # ✅ Chỉ dùng image, không dùng build
    container_name: docker-swarm-nodebe
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

networks:
  app-network:
    driver: overlay
