version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-ip-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
